---
title: "Dan Negrey | Shiny - BlastPoint Twitter Analysis"
output:
    flexdashboard::flex_dashboard:
        theme: bootstrap
        orientation: rows
        css: www/styles.css
        logo: www/dan-icon.png
        favicon: www/dan-icon.png
        navbar:
            - {icon: "fa-globe", href: "https://dnegrey.com", target: "_blank"}
            - {icon: "fa-linkedin", href: "https://www.linkedin.com/in/dnegrey", target: "_blank"}
            - {icon: "fa-github", href: "https://github.com/dnegrey", target: "_blank"}
            - {icon: "fa-twitter", href: "https://twitter.com/negreydan", target: "_blank"}
            - {icon: "fa-envelope", href: "mailto:dnegrey@gmail.com"}
runtime: shiny
---

```{r global, include=FALSE}
source("src/R/util/sourceFunctions.R")
sourceFunctions("src/R/util")
sink(file = "/dev/null")
suppressMessages(loadPackages("etc/PACKAGES"))
sink()
sourceFunctions("src/R/app")
load("pub/main.RData")
main$timelineDateRange <- datepart(range(main$timeline$created_at))
```

Sidebar {.sidebar}
==========

```{r, child = "src/Rmd/sidebar.Rmd"}
```

Home {data-icon=fa-home}
=========

```{r, child = "src/Rmd/home.Rmd"}
```

Tweets {data-icon=fa-twitter-square data-orientation=columns}
=========

```{r, child = "src/Rmd/tweets.Rmd"}
```

Followers {data-icon=fa-users}
=========

```{r, child = "src/Rmd/followers.Rmd"}
```

Hashtags {data-icon=fa-hashtag data-orientation=columns}
=========

```{r, child = "src/Rmd/hashtags.Rmd"}
```

Slides {data-icon=fa-slideshare .storyboard}
=========

```{r, child = "src/Rmd/slides.Rmd"}
```

Info {data-icon=fa-info-circle}
=========

```{r, child = "src/Rmd/info.Rmd"}
```
