Column {data-width=205}
----------

### **Tweet Filters** {id=hashtagsDataFilters}

```{r}
inputPanel(
    dateRangeInput(
        inputId = "hashtagsDataFilter_DateRange",
        label = "Date Range",
        start = main$timelineDateRange[1],
        end = main$timelineDateRange[2],
        min = main$timelineDateRange[1],
        max = main$timelineDateRange[2]
    ),
    checkboxGroupInput(
        inputId = "hashtagsDataFilter_TweetType",
        label = "Tweet Type",
        choices = c("Original", "Quote", "Retweet"),
        selected = c("Original", "Quote", "Retweet")
    ),
    radioButtons(
        inputId = "hashtagsDataFilter_Liked",
        label = "Liked",
        choices = c("Yes", "No", "Both"),
        selected = "Both",
        inline = TRUE
    ),
    radioButtons(
        inputId = "hashtagsDataFilter_Retweeted",
        label = "Retweeted",
        choices = c("Yes", "No", "Both"),
        selected = "Both",
        inline = TRUE
    ),
    sliderInput(
        inputId = "hashtagsDataFilter_MinCount",
        label = "Hashtag Minimum Tweet Count",
        min = 1,
        max = 10,
        value = 1,
        step = 1
    )
)
```

----------

```{r}
output$hashtagsFilteredTweetCount <- renderText(
    expr = {
        x <- hashtagSummaryTweeted()
        xn <- unique(x$total)
        y <- formatNumeric(xn, "num", 0)
        return(y)
    }
)
textOutput("hashtagsFilteredTweetCount")
```

<p style='font-size: 14pt; text-align: center;'>Filtered Tweets</p>

----------

*Reload page if word cloud fails to appear on load*

----------

```{r}
hashtagSummaryTweeted <- eventReactive(
    eventExpr = list(
        input$hashtagsDataFilter_DateRange,
        input$hashtagsDataFilter_TweetType,
        input$hashtagsDataFilter_Liked,
        input$hashtagsDataFilter_Retweeted,
        input$hashtagsDataFilter_MinCount
    ),
    valueExpr = hashtagSummary(
        x = main$timeline,
        dateRange = input$hashtagsDataFilter_DateRange,
        tweetType = input$hashtagsDataFilter_TweetType,
        liked = input$hashtagsDataFilter_Liked,
        retweeted = input$hashtagsDataFilter_Retweeted,
        minCount = input$hashtagsDataFilter_MinCount
    )
)
```

Column {data-width=795}
----------

### **Word Cloud** {id=hashtagsTweetedCloud}

```{r}
output$hashtagCloudTweeted <- renderWordcloud2(
    expr = {
        xc <- c(
            "#32B1E6",
            "#F9D230",
            "#0D2935",
            "#525252"
        )
        x <- hashtagSummaryTweeted()
        xc <- rep(xc, nrow(x))[1:nrow(x)]
        wordcloud2(
            data = x[1:2],
            fontFamily = "Roboto, sans-serif",
            color = xc
        )
    }
)
wordcloud2Output("hashtagCloudTweeted")
```
