Row
----------


### Tweets {id=homeValueBox_Tweets}

```{r}
valueBox(
    value = formatNumeric(main$user$statuses_count, "num"),
    icon = "fa-twitter",
    color = "#32B1E6"
)
```

### Followers {id=homeValueBox_Followers}

```{r}
valueBox(
    value = formatNumeric(main$user$followers_count, "num"),
    icon = "fa-users",
    color = "#32B1E6"
)
```

### Following {id=homeValueBox_Following}

```{r}
valueBox(
    value = formatNumeric(main$user$friends_count, "num"),
    icon = "fa-user-check",
    color = "#32B1E6"
)
```

### Likes {id=homeValueBox_Likes}

```{r}
valueBox(
    value = formatNumeric(main$user$favourites_count, "num"),
    icon = "fa-thumbs-up",
    color = "#32B1E6"
)
```

Row
----------

### **Tweet Type** {id=homePlot_TweetType}

```{r}
tweetTypePlot(
    x = tweetTypeSummary()
)
```

### **Tweet Source** {id=homePlot_TweetSource}

```{r}
tweetSourcePlot(
    x = tweetSourceSummary()
)
```

### 

Row
----------

### **Weekly Tweet Activity** {id=homePlot_TweetActivity}

```{r}
tweetCountPlot(
    x = tweetCountSummary("week")
)
```
