Column {data-width=205}
----------

### **Tweet Filters** {id=tweetsDataFilters}

```{r}
inputPanel(
    dateRangeInput(
        inputId = "tweetsDataFilter_DateRange",
        label = "Date Range",
        start = main$timelineDateRange[1],
        end = main$timelineDateRange[2],
        min = main$timelineDateRange[1],
        max = main$timelineDateRange[2]
    ),
    checkboxGroupInput(
        inputId = "tweetsDataFilter_TweetType",
        label = "Tweet Type",
        choices = c("Original", "Quote", "Retweet"),
        selected = c("Original", "Quote", "Retweet")
    ),
    radioButtons(
        inputId = "tweetsDataFilter_Liked",
        label = "Liked",
        choices = c("Yes", "No", "Both"),
        selected = "Both",
        inline = TRUE
    ),
    radioButtons(
        inputId = "tweetsDataFilter_Retweeted",
        label = "Retweeted",
        choices = c("Yes", "No", "Both"),
        selected = "Both",
        inline = TRUE
    ),
    selectInput(
        inputId = "tweetsDataFilter_TweetSource",
        label = "Tweet Source",
        choices = uniqueValues(main$timeline$source),
        multiple = TRUE
    )
)
```

----------

```{r}
output$tweetsFilteredTweetCount <- renderText(
    expr = {
        x <- tweetsData()
        xn <- nrow(x)
        y <- formatNumeric(xn, "num", 0)
        return(y)
    }
)
textOutput("tweetsFilteredTweetCount")
```

<p style='font-size: 14pt; text-align: center;'>Filtered Tweets</p>

----------

```{r}
inputPanel(
    downloadButton(
        "tweetsDataDownload",
        "Download Data (csv)"
    )
)
```

```{r}
tweetsData <- eventReactive(
    eventExpr = list(
        input$tweetsDataFilter_DateRange,
        input$tweetsDataFilter_TweetType,
        input$tweetsDataFilter_Liked,
        input$tweetsDataFilter_Retweeted,
        input$tweetsDataFilter_TweetSource
    ),
    valueExpr = tweetsDataFilter(
        x = main$timeline,
        dateRange = input$tweetsDataFilter_DateRange,
        tweetType = input$tweetsDataFilter_TweetType,
        liked = input$tweetsDataFilter_Liked,
        retweeted = input$tweetsDataFilter_Retweeted,
        tweetSource = input$tweetsDataFilter_TweetSource
    )
)
```

```{r}
output$tweetsDataDownload <- downloadHandler(
    filename = function() {
        "Filtered_Tweets.csv"
    },
    content = function(file) {
        xd <- tweetsData()
        xd$hashtags <- unlist(lapply(xd$hashtags, function(v){
            vo <- NA_character_
            if (!all(is.na(v))) {
                v <- v[!is.na(v)]
                vo <- paste(v, collapse = "; ")
            }
            return(vo)
        }))
        xd$mentions_screen_name <- unlist(lapply(xd$mentions_screen_name, function(v){
            vo <- NA_character_
            if (!all(is.na(v))) {
                v <- v[!is.na(v)]
                vo <- paste(v, collapse = "; ")
            }
            return(vo)
        }))
        write.csv(
            x = xd,
            file = file,
            na = "",
            row.names = FALSE
        )
    }
)
```

Column {data-width=795}
----------

### **Data Table** {id=tweetsDataTable}

```{r}
output$tweetsDataDT <- renderDT(
    expr = tweetsDT(
        x = tweetsData()
    )
)
DTOutput("tweetsDataDT")
```
